### ISSUE TITLE
I am really confused since i am not a good of a coder

### ISSUE THREAD

**Issue by fluffy29922** [Tomato6966/discord-chat-bot#1]
Hi bro i am getting this for some reason when i type %stats
EnmapPathError: The key "802833128456323102" does not exist in the enmap "chatbot"
    at Map.[check] (/home/runner/discord-chat-bot-1/node_modules/enmap/src/index.js:1047:13)
    at Map.get (/home/runner/discord-chat-bot-1/node_modules/enmap/src/index.js:340:19)
    at Object.run (/home/runner/discord-chat-bot-1/commands/🔰 Info/stats.js:16:39)
    at module.exports (/home/runner/discord-chat-bot-1/events/guild/message.js:107:17)
    at Client.emit (events.js:326:22)
    at MessageCreateAction.handle (/home/runner/discord-chat-bot-1/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/discord-chat-bot-1/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/discord-chat-bot-1/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/runner/discord-chat-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/runner/discord-chat-bot-1/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)

**Comment by Tomato6966** [comment]
ensure the db first lol

**Comment by Pro-Nil** [comment]
what do you mean by ensure db ? coz am also getting same error
